# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('article_description', models.CharField(max_length=500, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('article_title_img', models.CharField(max_length=50)),
                ('article_text', models.TextField()),
                ('article_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-article_date'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_name', models.CharField(default='\u0410\u043d\u043e\u043d\u0438\u043c', max_length=50, verbose_name='\u0412\u0430\u0448\u0435 \u0438\u043c\u044f')),
                ('comments_text', models.TextField(verbose_name='\u0412\u0430\u0448 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('comments_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
